### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by jyfan1104** [muzishen/RCDMs#2]
Nice projrect.How soon will the code be released？

**Comment by muzishen** [comment]
A little busy lately, maybe by the end of the month? 
If not by the end of the month, then by the middle of next month. I'm sorry

**Comment by muzishen** [comment]
Hi, we have released the code.

**Comment by johndpope** [comment]
looks like you will need to reference the older repos  - i found this file and datasets there.
https://github.com/xichenpan/ARLDM?tab=readme-ov-file

Traceback (most recent call last):
  File "/media/oem/12TB/RCDMs/train_stage1.py", line 26, in <module>
    from mydatasets.flintstones import FlintDataset,Collate_fn
  File "/media/oem/12TB/RCDMs/mydatasets/flintstones.py", line 11, in <module>
    from src.blip_override.blip import init_tokenizer
ModuleNotFoundError: No module named 'src.blip_override'
Traceback (most recent call last):
  File "/media/oem/12TB/RCDMs/train_stage1.py", line 26, in <module>
    from mydatasets.flintstones import FlintDataset,Collate_fn
  File "/media/oem/12TB/RCDMs/mydatasets/flintstones.py", line 11, in <module>
    from src.blip_override.blip import init_tokenizer
ModuleNotFoundError: No module named 'src.blip_override'
Traceback (most recent call last):
  File "/media/oem/12TB/RCDMs/train_stage1.py", line 26, in <module>
    from mydatasets.flintstones import FlintDataset,Collate_fn
  File "/media/oem/12TB/RCDMs/mydatasets/flintstones.py", line 11, in <module>
    from src.blip_override.blip import init_tokenizer
ModuleNotFoundError: No module named 'src.blip_override'
Traceback (most recent call last):
  File "/media/oem/12TB/RCDMs/train_stage1.py", line 26, in <module>
    from mydatasets.flintstones import FlintDataset,Collate_fn
  File "/media/oem/12TB/RCDMs/mydatasets/flintstones.py", line 11, in <module>
    from src.blip_override.blip import init_tokenizer
ModuleNotFoundError: No module named 'src.blip_override'
Traceback (most recent call last):
  File "/media/oem/12TB/RCDMs/train_stage1.py", line 26, in <module>
    from mydatasets.flintstones import FlintDataset,Collate_fn
  File "/media/oem/12TB/RCDMs/mydatasets/flintstones.py", line 11, in <module>
    from src.blip_override.blip import init_tokenizer
ModuleNotFoundError: No module named 'src.blip_override'
Traceback (most recent call last):
  File "/media/oem/12TB/RCDMs/train_stage1.py", line 26, in <module>
    from mydatasets.flintstones import FlintDataset,Collate_fn
  File "/media/oem/12TB/RCDMs/mydatasets/flintstones.py", line 11, in <module>
    from src.blip_override.blip import init_tokenizer
ModuleNotFoundError: No module named 'src.blip_override'
2024-08-09 04:19:29.538107: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/media/oem/12TB/RCDMs/train_stage1.py", line 26, in <module>
    from mydatasets.flintstones import FlintDataset,Collate_fn
  File "/media/oem/12TB/RCDMs/mydatasets/flintstones.py", line 11, in <module>
    from src.blip_override.blip import init_tokenizer
ModuleNotFoundError: No module named 'src.blip_override'
Traceback (most recent call last):
  File "/media/oem/12TB/RCDMs/train_stage1.py", line 26, in <module>
    from mydatasets.flintstones import FlintDataset,Collate_fn
  File "/media/oem/12TB/RCDMs/mydatasets/flintstones.py", line 11, in <module>
    from src.blip_override.blip import init_tokenizer
ModuleNotFoundError: No module named 'src.blip_override'
W0809 04:19:30.887000 133373634320192 torch/distributed/elastic/multiproce

**Comment by muzishen** [comment]
thanks u , we have fixed it.
